//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Xml.Serialization;

namespace YouSendIt.Entities
{ // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("storageChanges", Namespace="", IsNullable=true)]
    public class StorageChanges {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("currentUsage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrentUsage { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("revision", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Revision { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("revisionCount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long RevisionCount { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statusDisplay", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StatusDisplay { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("storageQuota", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorageQuota { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("workspaceId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WorkspaceId { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("file", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StorageChangesFile[] Files
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("folder", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StorageChangesFolder[] Folders
        {
            get;
            set;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public class NewDataSet {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("storageChanges")]
        public StorageChanges[] Items { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("file", Namespace = "", IsNullable = true)]
    public class StorageChangesFile
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("createdOn", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreatedOn
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deleteStatus", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeleteStatus
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileId", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileId
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileName", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileName
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("folderId", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FolderId
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lastUpdatedOn", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastUpdatedOn
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("revision", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Revision
        {
            get;
            set;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("folder", Namespace = "", IsNullable = true)]
    public class StorageChangesFolder
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("createdOn", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreatedOn
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("folderId", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long FolderId
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("folderType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FolderType
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lastUpdatedOn", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastUpdatedOn
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("revision", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long Revision
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shareInvitationPending", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShareinvitationPending
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("size", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long Size
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("permissions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StorageChangesPermissions[] Permissions
        {
            get;
            set;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("permissions", Namespace = "", IsNullable = true)]
    public class StorageChangesPermissions
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wsPermissionName", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WsPermissionName
        {
            get;
            set;
        }
    }
}